### PR TITLE
Hotfix/json schema

### PR DESCRIPTION
**Pull request by wandmagic**
# Committer Notes

The Json schema generation has an issue with creating the names for deginitions.

This pull request adds rudimentary testing to compile a json schema as a function which is only possible for valid schemas.

currently there is a warning regarding the decimal type, and that is addressed by a pull request up-stream. 

https://github.com/usnistgov/metaschema/pull/572

### All Submissions:

- [ ] Have you followed the guidelines in our [Contributing](https://github.com/usnistgov/metaschema-xslt/blob/master/CONTRIBUTING.md) document?
- [ ] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/usnistgov/metaschema-xslt/pulls) for the same update/change?
- [ ] Have you squashed any non-relevant commits and commit messages? \[[instructions](https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History)\]
- [ ] Do all automated CI/CD checks pass?

### Changes to Core Features:

- [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your core changes, as applicable?
- [ ] Have you included examples of how to use your new feature(s)?
- [ ] Have you updated all [website](https://pages.nist.gov/metaschema) and readme documentation affected by the changes you made? Changes to the website can be made in the website/content directory of your branch.

### CODE REVIEW

**Review by JustKuzya — APPROVED** [review]
I like the idea of AJV validation.

**Comment by wendellpiez** [comment]
As I remarked to @wandmagic in another channel, I do *not* like adding a Node JS dependency here. This test needs to be conducted, but adding dependencies only creates more technical debt.

(But I think it could be a good thing in a calling repository. Maybe the OSCAL repository already has a call on `ajv -compile` or even a test.)

Any comments on #110?

**Comment by wandmagic** [comment]
Hey i've made the node JS dependency optional in the latest commit.
it can be called outside of the smoke tests and spec tests independently.

**Review by wendellpiez — COMMENTED** [review]
I wonder if an illustration of the intended result JSON Schema could be provided, along with a pointer to the metaschema source file from which it is derived.

This has to be unit tested; it is possible the path could be collapsed further (removing support for @prefer) following Metaschema adjustment in https://github.com/usnistgov/metaschema/issues/558.

Given copies of the source metaschema, the intended result and the current result (from a run), I can build a unit test that isolates this path logic and presents examples of the range of expected inputs.

This way when we patch the path logic we also expose assurance that it works (under many eyes), and we will not thrash.

Thanks for diligence so far @wandmagic

**Comment by wandmagic** [comment]
see the output of current develop branch
[invalid_develop.schema.json](https://github.com/usnistgov/metaschema-xslt/files/14668501/invalid_develop.schema.json)

and the output from this branch
[corrected.schema.json](https://github.com/usnistgov/metaschema-xslt/files/14668513/corrected.schema.json)

**Comment by wendellpiez** [comment]
Thanks much, @wandmagic

For transparency and the record, could I bother you also to provide code illustrations of the before-and-after?

This is mainly because I expect to provide this work with the unit testing to support it (validate and protect against regression), and it would save me a couple steps in writing it. But additionally because it makes the work easier to track for everyone.

**Comment by wandmagic** [comment]
the only substantial change is in the difference in output illustrated here:
this code change:
Screenshot 2024-03-23 at 7 21 21 PM

results in this difference in output.
Screenshot 2024-03-23 at 7 18 29 PM

**Comment by wendellpiez** [comment]
@wandmagic thanks for the snips, very helpful indeed for repro.

**Pull request closed without merging**
