### PR TITLE
hotfix schema id

### PR DESCRIPTION
**Pull request by wandmagic**
# Committer Notes

### All Submissions:

- [ ] Have you followed the guidelines in our [Contributing](https://github.com/usnistgov/metaschema-xslt/blob/master/CONTRIBUTING.md) document?
- [ ] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/usnistgov/metaschema-xslt/pulls) for the same update/change?
- [ ] Have you squashed any non-relevant commits and commit messages? \[[instructions](https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History)\]
- [ ] Do all automated CI/CD checks pass?

### Changes to Core Features:

- [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your core changes, as applicable?
- [ ] Have you included examples of how to use your new feature(s)?
- [ ] Have you updated all [website](https://pages.nist.gov/metaschema) and readme documentation affected by the changes you made? Changes to the website can be made in the website/content directory of your branch.

### CODE REVIEW

**Review by wendellpiez — APPROVED** [review]
This is a pretty clean and simple change now and I am rethinking whether the formal regression test should be a blocker, in view of the need for this correction (as I understand it). If this is a breaking change we can fix it, and the testing work can continue on its own track.

@wandmagic I am not missing anything, do you think? (Comments @nikitawootten-nist ?) Should we meet if only briefly to review the impact (see the correction) in the OSCAL runtime?

**Comment by iMichaela** [comment]
@wendellpiez - this finding and fix is the result of @wandmagic review of OSCAL [dependabot PR#2001] (https://github.com/usnistgov/OSCAL/pull/2001). We would like to use the latest metaschema-xslt with the OSCAL v1.2.0 release candidates. @wandmagic - Is this PR a blocker for the [dependabot PR#2001] (https://github.com/usnistgov/OSCAL/pull/2001) since #2001 was not approved? @wendellpiez - Is this PR not an improvement?  Thank you for working together to roll the ball and support the OSCAL v1.2.0 improved release candidate.

**Comment by wandmagic** [comment]
without this PR the json schemas do not generate correctly, and oscal repo does need a working version. 
once this repo becomes stable it would be good to tag a release and update the submodule upstream.

**Comment by wendellpiez** [comment]
I would like to work this further in the context of unit testing *all* the schema production, but I do not want that to be a blocker at this time.

If @wandmagic and @nikitawootten-nist have tested runtimes and are confident that

- the generated JSON Schemas are now 'correct' to a documented spec (where?)
- they function correctly vis-a-vis tested document sets

then by all means let's proceed with this.

If it blows up, we know how to repair the deeper problem - bring [Schema field testing](https://github.com/usnistgov/metaschema-xslt/issues/110) on line.

**Comment by iMichaela** [comment]
> I would like to work this further in the context of unit testing _all_ the schema production, but I do not want that to be a blocker at this time.
> 
> If @wandmagic and @nikitawootten-nist have tested runtimes and are confident that
> 
> * the generated JSON Schemas are now 'correct' to a documented spec (where?)
> * they function correctly vis-a-vis tested document sets
> 
> then by all means let's proceed with this.
> 
> If it blows up, we know how to repair the deeper problem - bring [Schema field testing](https://github.com/usnistgov/metaschema-xslt/issues/110) on line.

Thank you, @wendellpiez . Will you merge it any time soon? When you will do so, I will recreate the dependabot/metaschema-xslt in the OSCAL repo so we can proceed to the next step on getting ready the release candidates. I tested/generated locally the release candidates with @nikitawootten-nist 's branch created from the develop branch. I do not know fi @nikitawootten-nist tested the hotfix. I did not... Do you want me to?

**Pull request merged**
