### PR TITLE
External Metaschema linking to all the atomic types. Fixed #15

### LINKED ISSUE #15: Syntax Documentation Improvements
# User Story:

As an OSCAL implementer, when reviewing the OSCAL syntax documents it would be helpful to have a summary of flags, fields, and assemblies first (as they appeared in the original version of the generated documentation), then followed by the expanded view as it appears now. This is especially important with larger assemblies. It is currently very difficult to find fields farther down in the assembly.

It would also be helpful to have improved visual delimiters as to where flags end and fields/sub-assemblies begin, as well as where the top-level assembly ends. 

## Goals:

* Increase usability by enabling a summary view of an assembly before the expanded view 
* Provider better visual delimiters as to where one assembly ends and another begins, as well as within the assembly to differentiate flags from fields/sub-assemblies, and to further differentiate the child syntax of sub-assemblies.

## Dependencies:

None.

## Acceptance Criteria

- [ ] All [website](https://pages.nist.gov/metaschema) and readme documentation affected by the changes in this issue have been updated. Changes to the website can be made in the docs/content directory of your branch.
- [ ] A Pull Request (PR) is submitted that fully addresses the goals of this User Story. This issue is referenced in the PR.
- [ ] The CI-CD build process runs without any reported errors on the PR. This can be confirmed by reviewing that all checks have passed in the PR.

### PR DESCRIPTION
**Pull request by JustKuzya**
# Committer Notes

Fixed the simple and extended type links to point to metaschema types page

This PR also fixes links between pages within the Hugo XProc. This is accomplished via a new parameter that the user is expected to pass in. For details see the integration PR https://github.com/usnistgov/OSCAL-Reference/pull/20.

### All Submissions:

- [x] Have you followed the guidelines in our [Contributing](https://github.com/usnistgov/metaschema-xslt/blob/master/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/usnistgov/metaschema-xslt/pulls) for the same update/change?
- [x] Have you squashed any non-relevant commits and commit messages? \[[instructions](https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History)\]
- [x] Do all automated CI/CD checks pass?

### Changes to Core Features:

- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- ~Have you written new tests for your core changes, as applicable?~
- ~Have you included examples of how to use your new feature(s)?~
- ~Have you updated all [website](https://pages.nist.gov/metaschema) and readme documentation affected by the changes you made? Changes to the website can be made in the website/content directory of your branch.~

### CODE REVIEW

**Comment by nikitawootten-nist** [comment]
Regarding problem 1: The issue is that Metaschema has deprecated the old names of some datatypes. Elsewhere in the codebase this is solved using a "type map" to normalize the datatype names: https://github.com/usnistgov/metaschema-xslt/blob/034e92b3d3dd4140ab2682d509a0c1812254f597/src/schema-gen/XSD/make-metaschema-xsd.xsl#L54

Using the same approach as above we should be able to normalize the names. More to follow.

**Comment by nikitawootten-nist** [comment]
@JustKuzya I'm working on a solution to problem 1, expect a PR into your PR soon.

**Comment by nikitawootten-nist** [comment]
https://github.com/JustKuzya/metaschema-xslt/pull/1 fixes the deprecated names in links!

Also regarding the second issue, it seems the behavior is limited to Chrome under certain conditions (it does not happen always, chrome bug?)

**Review by JustKuzya — COMMENTED** [review]
Looks like it is in the right place

**Comment by aj-stein-nist** [comment]
@JustKuzya what's the status on this, do you need help on the merge conflict?

**Comment by JustKuzya** [comment]
No, thank you, just need to te a look at it - was busy on Blossom with Nikita until a few seconds ago

It looks like I don't have the access to resolve conflicts in this repo, meanwhile the PR is gone from mine. Maybe the problem is that I forked from @wendellpiez repo before the usnistgov/metaschema-xslt even existed? I'm clearly warned that: 

"This branch has conflicts that must be resolved
Only those with [write access](https://docs.github.com/articles/what-are-the-different-access-permissions) to this repository can merge pull requests."

Additionally, in allegedly conflicting file src/document/write-hugo-metaschema-docs.xpl I can only see changes in my view, not the merge conflicts.

**Comment by aj-stein-nist** [comment]
I'll work through the merge conflict @JustKuzya and ping you in a little while.

**Comment by JustKuzya** [comment]
Went a few times over the conflicting merge spots and made sure that the site builds and runs

**Comment by aj-stein-nist** [comment]
> Went a few times over the conflicting merge spots and made sure that the site builds and runs

Sorry I didn't check sooner, I got sidetracked. Looks good so far. I will run through it myself and hopefully approve shortly.

**Review by aj-stein-nist — CHANGES_REQUESTED** [review]
It appears we have some minor issues around the reference links not to the simple Metaschema types (i.e. token, string, datetime work), but the related fixes around complex types in Metaschema (such as the OSCAL assembly group in catalog with the embedded hyperlink of "an array of group objects") don't work and the URLs 404.

image

If I click in group in catalog, I get the following URL.

http://localhost:1313/OSCAL-Reference/models/develop/json-reference/#/catalog/groups

Whereas we need to specify the complete catalog in the URL or the specific model. Observe the asterisks.

http://localhost:1313/OSCAL-Reference/models/develop/**complete**/json-reference/#/catalog/groups

http://localhost:1313/OSCAL-Reference/models/develop/**catalog**/json-reference/#/catalog/groups

Had you intended to fix this? I thought so because it was discussed in a standup a few days ago, or perhaps I misunderstood. I guess we need to hop on a call when we can.

**Comment by nikitawootten-nist** [comment]
> Had you intended to fix this? I thought so because it was discussed in a standup a few days ago, or perhaps I misunderstood. I guess we need to hop on a call when we can.

@aj-stein-nist just to be clear, were you testing with the patched OSCAL-Reference (https://github.com/usnistgov/OSCAL-Reference/pull/20)? The link changes do not take effect unless the change to the `generate_modeldoc.sh` script are made.

**Comment by aj-stein-nist** [comment]
> > Had you intended to fix this? I thought so because it was discussed in a standup a few days ago, or perhaps I misunderstood. I guess we need to hop on a call when we can.
> 
> @aj-stein-nist just to be clear, were you testing with the patched OSCAL-Reference ([usnistgov/OSCAL-Reference#20](https://github.com/usnistgov/OSCAL-Reference/pull/20))? The link changes do not take effect unless the change to the `generate_modeldoc.sh` script are made.

Sorry 1 AM reviews are silly. Did the modeldoc changes how the paths are input into this? I forgot I `git cleaned` and reverted on the submodule, maybe I also did that on the parent repo as well. In that case, belay that remark!

**Review by aj-stein-nist — APPROVED** [review]

**Comment by nikitawootten-nist** [comment]
Before you merge I'm giving a cursory look myself.

Edit I have confirmed the links have been corrected and are working as intended:
Screenshot 2023-09-21 at 10 44 16 AM

**Comment by nikitawootten-nist** [comment]
@wendellpiez I am getting a warning from Saxon that I did not notice before:
```
Warning at xsl:stylesheet on line 5 column 31 of datatypes.xsl:
   Stylesheet module
  file:/Users/naw2/Documents/repos/OSCAL-Reference/support/metaschema-xslt/src/common/datatypes.xsl is included or imported more than once. This is permitted, but may lead to errors or unexpected behavior
```

It seems to run fine and not any slower then before, should we be worried? Or should this warning be ignored? I'm guessing there's no way to `IFNDEF` imports in XSLT?

**Comment by JustKuzya** [comment]
We probably should encourage for the imports and includes to be at the top of the file to avoid these warnings - I remember the XSLT parsers complaining or even producing errors in the past, at various level of warning setting. Probably the same or similar thing.

DC

________________________________

**Comment by wendellpiez** [comment]
To be really strict:
- We would mandate all `xsl:import` and `xsl:include` happen at the top to help prevent surprises
- We would code each XSLT to fail on match clashes
- We would test both of these with Schematron or XSLT

To guarantee failure on match clashes:

```
<xsl:mode on-multiple-match="fail"/>
```

which ensure that with an ambiguous match the processor will throw an error, not take the latter one.

This goes far to eliminate the chances that template ordering can have any effect on results, without warnings. (It should be Saxon's setting anyway.)

The order of `xsl:import` will still determine **import precedence** for purposes of matching templates -- while that does not apply to `xsl:include` or templates included thereby.

**Review by nikitawootten-nist — APPROVED** [review]

**Pull request merged**
